name: 'Meeting Assistant'
author: 'Benjamin-Frost'
description: 'Assigns leader for next meeting and outputs telegram name of selected user'

inputs:
  issue-number:
    description: 'Number of issue meeting'
    required: true
  users:
    description: 'JSON array of user objects with keys: name, github, telegram'
    required: true
outputs:
  telegram:
    description: 'Telegram name of selected user'

runs:
  using: 'node12'
  main: 'dist/index.js'
