coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        flags:
          - annotation-server
          - lab-server
    patch:
      default:
        target: auto
        threshold: 10%
        flags:
          - annotation-server
          - lab-server

flag_management:
  individual_flags:
    - name: annotation-server
      paths:
        - annotation-server/src
      carryforward: true
    - name: lab-server
      paths:
        - lab-server/src
      carryforward: true
