services:
  lab-server:
    build: .
    ports:
      - 8081:3000
    depends_on:
      - postgres
    profiles:
      - production

  postgres:
    image: postgres:13
    volumes:
      - lab_server_db:/var/lib/postgresql/data
    ports:
      - 5678:5432
    environment:
      - POSTGRES_USER=${LAB_SERVER_DB_USER}
      - POSTGRES_PASSWORD=${LAB_SERVER_DB_PASS}
      - POSTGRES_DB=${LAB_SERVER_DB_NAME}

volumes:
  lab_server_db:
