services:
  api:
    build:
      dockerfile: ./lab-server/Dockerfile
      context: ../
    env_file: .env
    ports:
      - 8081:3001
    depends_on:
      - lab-server-db
    profiles:
      - production

  lab-server-db:
    image: postgres:13
    volumes:
      - lab_server_db:/var/lib/postgresql/data
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=${LAB_SERVER_DB_USER}
      - POSTGRES_PASSWORD=${LAB_SERVER_DB_PASS}
      - POSTGRES_DB=${LAB_SERVER_DB_NAME}

  keycloak:
    image: jboss/keycloak:16.1.0
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak_db
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
    ports:
      - 28080:8080
    depends_on:
      - keycloak-db
    profiles:
      - local

  keycloak-db:
    image: postgres:13
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    ports:
      - 25433:5432
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASS}
      - POSTGRES_DB=keycloak_db
    profiles:
      - local

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_db:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    profiles:
      - local

volumes:
  lab_server_db:
  minio_db:
  keycloak_db:
