services:
  api:
    build: .
    volumes:
      # mapped folder in the container needs to match the working dir's parent directory found in the Dockerfile
      - ../assets:/usr/src/assets:ro
      # mapped folder in the container needs to match the working dir found in the Dockerfile
      - ./data:/usr/src/app/data:ro
    ports:
      - 8080:3000
    depends_on:
      - annotation-server-db
    profiles:
      - production

  annotation-server-db:
    image: postgres:13
    volumes:
      - annotation_server_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${ANNOTATION_DB_USER}
      - POSTGRES_PASSWORD=${ANNOTATION_DB_PASS}
      - POSTGRES_DB=${ANNOTATION_DB_NAME}

volumes:
  annotation_server_db:
