services:
  api:
    build: .
    volumes:
      # mapped folder in the container needs to match the working dir's parent directory found in the Dockerfile
      - ../assets:/usr/src/assets:ro
    ports:
      - 8080:3000
    depends_on:
      - postgres
    profiles:
      - production

  postgres:
    image: postgres:13
    volumes:
      - annotation_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${ANNOTATION_DB_USER}
      - POSTGRES_PASSWORD=${ANNOTATION_DB_PASS}
      - POSTGRES_DB=${ANNOTATION_DB_NAME}

volumes:
  annotation_db:



# ANNOTATION_DB_HOST=localhost
# ANNOTATION_DB_PORT=5432
# ANNOTATION_DB_USER=postgres
# ANNOTATION_DB_PASS=postgres
# ANNOTATION_DB_NAME=annotation_db
