name: Annotation Server

on:
  push:
    paths:
      - '.github/workflows/annotation-server.yml'
      - 'annotation-server/**'
  pull_request:
    paths:
      - '.github/workflows/annotation-server.yml'
      - 'annotation-server/**'

defaults:
  run:
    working-directory: ./annotation-server

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint

  test:
    name: Test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test

  build:
    name: Build
    needs: [lint, test]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build

  deploy:
    name: Deploy
    needs: [lint, test, build]
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/frasecys/annotation-server
            git pull
            docker-compose --profile production up --build --force-recreate --no-deps -d
