name: App

on:
  push:
    paths:
      - '.github/workflows/app.yml'
      - 'app/**'
  pull_request:
    paths:
      - '.github/workflows/app.yml'
      - 'app/**'

env:
  JAVA_VERSION: 12.x
  FLUTTER_CHANNEL: stable
  FLUTTER_VERSION: 2.5.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    # TODO(Benjamin-Frost): Enable this when we have tests
    if: 'false'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter test

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build apk

  build-ios:
    name: Build iOS Package
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build ios --release --no-codesign
