name: Lab Server

on:
  push:
    paths:
      - ".github/workflows/lab-server.yml"
      - "lab-server/**"
  pull request:
    paths:
      - ".github/workflows/lab-server.yml"
      - "lab-server/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lab-server
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lab-server
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test

build:
  name: Build
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./lab-server
  steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn build
