name: Lab Server

on:
  push:
    paths:
      - ".github/workflows/lab-server.yml"
      - "lab-server/**"
  pull_request:
    paths:
      - ".github/workflows/lab-server.yml"
      - "lab-server/**"

defaults:
  run:
    working-directory: ./lab-server

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint

  test:
    name: Test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test

  build:
    name: Build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build

  deploy:
    name: Deploy
    needs: [lint, test, build]
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/frasecys/lab-server
            git pull
            
            # use following with database 
            #docker compose up
            #yarn start:prod
            
            # use following w/o database
            docker build -t lab-server .
            docker run -p 8080:3000 -t lab-server
