name: Lab Server

on:
  push:
    paths:
      - '.github/workflows/lab-server.yml'
      - 'lab-server/**'

defaults:
  run:
    working-directory: ./lab-server

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    env:
      KEYCLOAK_AUTH_SERVER_URL: ${{ secrets.KEYCLOAK_AUTH_SERVER_URL }}
      KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
      KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      KEYCLOAK_SECRET: ${{ secrets.KEYCLOAK_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test:e2e:cov
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: lab-server/coverage

  codecov:
    name: Generate Code Coverage Report
    needs: [test-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: lab-server/coverage
      - uses: codecov/codecov-action@v2
        with:
          flags: lab-server
          directory: lab-server/coverage
          fail_ci_if_error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build

  deploy:
    name: Deploy
    needs: [lint, test-e2e, build]
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git fetch origin main
            git reset --hard origin/main
            cd lab-server
            docker-compose --profile production up --build --force-recreate --no-deps -d
