name: Lint Markdown

on:
  push:
    paths:
     - '**.md'
  pull_request:
    paths:
     - '**.md'

jobs:
  lint-markdown:
      name: Markdown-Lint
      runs-on: [self-hosted, linux]
      steps:
      - uses: actions/checkout@v2
      - name: Run Markdown-Lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: './**/*.md'
