name: Meeting Assistant

# on:
#   schedule:
#     - cron: '0 12 * * 5'

on: push

jobs:
  assign_leader:
    # runs-on: [self-hosted, Linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./other/meeting-assistant
        with:
          issue-number: 5
          users: ${{ secrets.BP_USERS }}
