name: Meeting Assistant

on:
  schedule:
    - cron: '0 12 * * 5'

jobs:
  select_next_student:
    runs-on: ubuntu-latest
    outputs:
      telegram: ${{ steps.meeting_assistant.outputs.telegram }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./miscellaneous/meeting-assistant
        id: meeting_assistant
        with:
          users: ${{ secrets.BP_USERS }}

  send_telegram_message:
    runs-on: ubuntu-latest
    needs: [select_next_student]
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Hi @${{ needs.select_next_student.outputs.telegram }},
            friendly reminder that you are responsible for the Sprint Planning next Monday 🚀
