name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  RELEASE_SUBJECT: PharMe

jobs:
  create-release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get release tag
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/changelog.config.js
      - uses: softprops/action-gh-release@v1
        name: Release
        with:
          name: ${{ env.RELEASE_SUBJECT }} ${{ steps.get_version.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
